// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0");
user_pref("extensions.lastPlatformVersion", "69.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"d98d85b8-a3db-416c-9511-a20d2b6f7c3a\",\"fxmonitor@mozilla.org\":\"58483e6c-478f-4e72-9e99-eae6834bc51c\",\"screenshots@mozilla.org\":\"3dad39f5-5227-4fe4-aec9-3ad5b4aad62b\",\"webcompat-reporter@mozilla.org\":\"6c0153ab-6430-4b04-9917-25d77dd2712f\",\"webcompat@mozilla.org\":\"94bd60e0-a597-4aa6-a5a8-0d3af702c66d\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.content.tempDirSuffix", "2a0d201e-4f56-4838-86fc-cdb3df759c61");
user_pref("security.sandbox.plugin.tempDirSuffix", "c4cc4e57-bf4f-42db-af9b-df9e2f73ff1a");
user_pref("toolkit.telemetry.previousBuildID", "20190831223935");
